# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    env(HOSTNAME): local

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $mocksBaseUrl: '%env(MOCKS_BASE_URL)%'
            string $redisUrl: '%env(REDIS_URL)%'
            string $workerId: '%env(HOSTNAME)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'
