# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    env(HOSTNAME): local
    env(ARENA_SIZE): demo

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $mocksBaseUrl: '%env(MOCKS_BASE_URL)%'
            string $redisUrl: '%env(REDIS_URL)%'
            string $scalerUrl: '%env(SCALER_URL)%'
            string $workerId: '%env(HOSTNAME)%'
            int $maxWorkers: '%env(int:MAX_WORKERS)%'
            App\Domain\Venue\ArenaSize $arenaSize: '%env(enum:App\Domain\Venue\ArenaSize:ARENA_SIZE)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Domain/'
            - '../src/Kernel.php'
