# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    http_client:
        default_options:
            timeout: 3
            max_duration: 4
    secret: '%env(APP_SECRET)%'

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
